In [75]:
import pandas as pd
import numpy as np
df1=pd.read_csv('/content/Uncleaned_DS_jobs.csv')

In [76]:
df1.sample(10)

,index,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
446,446,Data Scientist - Intermediate,$69K-$116K (Glassdoor est.),Job description:\n\nCreate and maintain code f...,Envision LLC\n4.5,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,1994,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1
332,332,Machine Learning Engineer/Scientist,$79K-$147K (Glassdoor est.),About the Position\n\n\nJane Street is seeking...,Jane Street\n4.8,"New York, NY","New York, NY",501 to 1000 employees,2000,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1
253,253,Data Scientist,$90K-$124K (Glassdoor est.),You are key to helping global clients make bet...,Gallup\n4.1,"New York, NY","Washington, DC",1001 to 5000 employees,1935,Company - Private,Consulting,Business Services,Unknown / Non-Applicable,"Advisory Board, Booz Allen Hamilton, McKinsey ..."
463,463,Data Analyst - Unilever Prestige,$69K-$116K (Glassdoor est.),Data Analyst - Unilever Prestige\nJob Code\n\n...,Dermalogica\n3.8,"Carson, CA","Carson, CA",201 to 500 employees,1986,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),"IMAGE Skincare, Aveda, Kiehl's"
370,370,AI Ops Data Scientist,$112K-$116K (Glassdoor est.),"Company\n\nAstraZeneca is a global, innovation...",AstraZeneca\n4.0,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
568,568,Data Scientist,$128K-$201K (Glassdoor est.),"At Kibo, we provide cloud commerce solutions i...",Kibo,"Philadelphia, PA","Marbella, Spain",Unknown,-1,Company - Public,-1,-1,Unknown / Non-Applicable,-1
141,141,Tableau Data Engineer 20-0117,$90K-$109K (Glassdoor est.),"We are Relativity. A market-leading, global te...",Relativity\n3.7,"Chicago, IL","Chicago, IL",1001 to 5000 employees,2001,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
411,411,Data Scientist,$124K-$198K (Glassdoor est.),Our entertainment company is seeking a Data Sc...,Evolvinc,"Burbank, CA","Los Angeles, CA",1 to 50 employees,2005,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1
49,49,Data Scientist,$75K-$131K (Glassdoor est.),Company Description:\nWhats it like to work at...,Quick Base\n4.3,"Cambridge, MA","Cambridge, MA",201 to 500 employees,1999,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
408,408,Data Scientist,$124K-$198K (Glassdoor est.),Type: Full Time\nClearance: TS/ w Polygraph\nE...,"Visionist, Inc.\n4.9","Columbia, MD","Columbia, MD",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),-1

In [77]:
print(df1.shape)
print('-----------------------------------------------------')
print(df1.columns)
print('-----------------------------------------------------')
print('null values\n',df1.isnull().sum())
print('-----------------------------------------------------')
print('duplicates\n', df1.duplicated().sum())
print('-----------------------------------------------------')
print(df1.info())

(672, 14)
-----------------------------------------------------
Index(['index', 'Job Title', 'Salary Estimate', 'Job Description',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')
-----------------------------------------------------
null values
 index                0
Job Title            0
Salary Estimate      0
Job Description      0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64
-----------------------------------------------------
duplicates
 0
-----------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Company Name       672 non-null    object
 5   Location           672 non-null    object
 6   Headquarters       672 non-null    object
 7   Size               672 non-null    object
 8   Founded            672 non-null    int64
 9   Type of ownership  672 non-null    object
 10  Industry           672 non-null    object
 11  Sector             672 non-null    object
 12  Revenue            672 non-null    object
 13  Competitors        672 non-null    object
dtypes: int64(2), object(12)
memory usage: 73.6+ KB
None

- No null values
- No duplicate values in dataset

In [78]:
df1.nunique()

index                672
Job Title            172
Salary Estimate       30
Job Description      489
Company Name         432
Location             207
Headquarters         229
Size                   9
Founded              103
Type of ownership     13
Industry              58
Sector                23
Revenue               14
Competitors          108
dtype: int64

# Data Cleaning

In [79]:
# delating the index column as it doesnot give any information
df1.drop('index',axis=1,inplace=True)

In [80]:
print('duplicates\n', df1.duplicated().sum())

duplicates
 13

In [81]:
# After removing index it is observed we have 13 dulpicates, deleting these duplicates
df1.drop_duplicates(inplace=True)

In [82]:
df1.reset_index(inplace=True)

In [83]:
df1.shape

(659, 14)

In [84]:
df1.drop('index',axis=1,inplace=True)

In [85]:
df1.shape

(659, 13)

In [86]:
top_industries = df1['Industry'].value_counts().nlargest(6)
top_industries

Biotech & Pharmaceuticals                  66
IT Services                                61
-1                                         60
Computer Hardware & Software               56
Aerospace & Defense                        46
Enterprise Software & Network Solutions    43
Name: Industry, dtype: int64

In [87]:
# simplifying first column
df1['Job Title'].unique()

array(['Sr Data Scientist', 'Data Scientist',
       'Data Scientist / Machine Learning Expert',
       'Staff Data Scientist - Analytics',
       'Data Scientist - Statistics, Early Career', 'Data Modeler',
       'Experienced Data Scientist', 'Data Scientist - Contract',
       'Data Analyst II', 'Medical Lab Scientist',
       'Data Scientist/Machine Learning', 'Human Factors Scientist',
       'Business Intelligence Analyst I- Data Insights',
       'Data Scientist - Risk', 'Data Scientist-Human Resources',
       'Senior Research Statistician- Data Scientist', 'Data Engineer',
       'Associate Data Scientist', 'Business Intelligence Analyst',
       'Senior Analyst/Data Scientist', 'Data Analyst',
       'Machine Learning Engineer', 'Data Analyst I',
       'Scientist - Molecular Biology',
       'Computational Scientist, Machine Learning',
       'Senior Data Scientist', 'Jr. Data Engineer',
       'E-Commerce Data Analyst', 'Data Analytics Engineer',
       'Product Data Scientist - Ads Data Science',
       'Data Scientist - Intermediate', 'Global Data Analyst',
       'Data & Machine Learning Scientist',
       'Data Scientist - Machine Learning', 'Data Engineer (Remote)',
       'Data Scientist, Applied Machine Learning - Bay Area',
       'Principal Data Scientist', 'Business Data Analyst',
       'Purification Scientist', 'Data Engineer, Enterprise Analytics',
       'Data Scientist 3 (718)', 'Real World Science, Data Scientist',
       'Data Scientist - Image and Video Analytics',
       'Data Science Manager, Payment Acceptance - USA',
       'Data Scientist / Applied Mathematician',
       'Patient Safety- Associate Data Scientist',
       '(Sr.) Data Scientist -', 'Data Scientist, Kinship - NYC/Portland',
       'Applied Technology Researcher / Data Scientist',
       'Health Data Scientist - Biomedical/Biostats',
       'Staff Data Scientist', 'Sr Data Engineer (Sr BI Developer)',
       'Lead Data Scientist', 'RFP Data Analyst',
       'Data Scientist (TS/SCI)', 'Software Engineer - Data Science',
       'Data Analyst/Engineer', 'NGS Scientist', 'Senior Data Engineer',
       'Sr. ML/Data Scientist - AI/NLP/Chatbot',
       'Data Integration and Modeling Engineer',
       'Tableau Data Engineer 20-0117', 'AI Data Scientist',
       'Research Scientist Patient Preferences (Remote)',
       'Scientist - Biomarker and Flow Cytometry', 'Analytics Manager',
       'Staff Scientist- Upstream PD',
       'Sr Scientist - Extractables & Leachables',
       'ELISA RESEARCH SCIENTIST (CV-15)', 'Say Business Data Analyst',
       'Geospatial Data Scientist', 'Computational Scientist',
       'Senior Data Analyst', 'Sr Data Analyst',
       'Machine Learning Scientist - Bay Area, CA',
       'Senior Data Scientist - Algorithms',
       'Senior Data & Machine Learning Scientist',
       'Research Scientist - Patient-Centered Research (Remote)',
       'Jr. Business Data Analyst (position added 6/12/2020)',
       'Sr. Data Scientist II',
       'Production Engineer - Statistics/Data Analysis',
       'Statistical Scientist', 'Computational Behavioral Scientist',
       'Principal Data Scientist - Machine Learning',
       'Principal Machine Learning Scientist',
       'Senior Data Scientist - R&D Oncology',
       'Health Plan Data Analyst, Sr',
       'Principal Scientist/Associate Director, Quality Control and Analytical Technologies',
       'Analytics - Business Assurance Data Analyst',
       'Senior Data Scientist – Image Analytics, Novartis AI Innovation Lab',
       'Data Science Instructor', 'Senior Business Intelligence Analyst',
       'In-Line Inspection Data Analyst',
       'Data Scientist - TS/SCI FSP or CI Required',
       'Data Scientist - TS/SCI Required',
       'Data Science Software Engineer',
       'ENGINEER - COMPUTER SCIENTIST - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING - SAN ANTONIO OR',
       'AI Ops Data Scientist', 'Intelligence Data Analyst, Senior',
       'Analytics Manager - Data Mart',
       'Data Modeler (Analytical Systems)',
       'Senior Machine Learning Scientist - Bay Area, CA',
       'Report Writer-Data Analyst', 'Staff Data Scientist - Pricing',
       'Equity Data Insights Analyst - Quantitative Analyst',
       'Operations Data Analyst', 'Software Data Engineer',
       'Real World Evidence (RWE) Scientist', 'Computer Scientist 1',
       'Environmental Data Science', 'Staff BI and Data Engineer',
       'Data Scientist - Statistics, Mid-Career',
       'Director of Data Science',
       'Data Engineer, Digital & Comp Pathology',
       'Manager / Lead, Data Science & Analytics',
       'Diversity and Inclusion Data Analyst',
       'Data Scientist Machine Learning', 'Chief Scientist',
       'Development Scientist, Voltaren',
       'Principal Data & Analytics Platform Engineer',
       'Machine Learning Engineer/Scientist',
       'Data Analyst - Unilever Prestige', 'VP, Data Science',
       'Data Engineer - Kafka', 'Decision Scientist',
       'Data Science All Star Program - Data Engineer Track',
       'Scientist - Machine Learning', 'Sr. Data Scientist',
       'Applied AI Scientist / Engineer',
       'Data Engineer (Analytics, SQL, Python, AWS)',
       'Senior Data Analyst - Finance & Platform Analytics',
       'Market Research Data Scientist',
       'IT Partner Digital Health Technology and Data Science',
       'Software Engineer (Data Scientist, C,C++,Linux,Unix) - SISW - MG',
       'Senior Clinical Data Scientist Programmer',
       'Computer Vision / Deep Learning Scientist',
       'Data Solutions Engineer - Data Modeler',
       'Data Scientist (TS/SCI w/ Poly)',
       'Weapons and Sensors Engineer/Scientist',
       'Applied Computer Scientist', 'Cloud Data Engineer (Azure)',
       'Lead Certified Clinical Laboratory Scientist - Saturday - Tuesday, 8:00pm - 6:30am shift',
       'Sr. Data Analyst',
       'Senior Scientist - Toxicologist - Product Integrity (Stewardship)',
       'Senior Machine Learning Engineer',
       'Data Scientist- Industrial Discrete Sector Industry',
       'Senior Principal Data Scientist (Python/R)',
       'Data Scientist(s)/Machine Learning Engineer',
       'Scientist / Group Lead, Cancer Biology',
       'Manager, Field Application Scientist, Southeast',
       'COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING',
       'Machine Learning Scientist / Engineer', 'Data Science Analyst',
       'COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUTER SCIENTIST - TRANSPORTATION TECHNOLOGY',
       'Software Engineer - Machine Learning & Data Science (Applied Intelligence Services Team)',
       'Clinical Data Analyst', 'Data Scientist Technical Specialist',
       'Data Science Manager', 'Big Data Engineer', 'Data Architect',
       'Aviation AI/ML Data Scientist', 'Machine Learning Engineer, Sr.',
       'Information Systems Engineering Specialist (Engineering Scientist)',
       'Scientist/Research Associate-Metabolic Engineering',
       'Vice President, Biometrics and Clinical Data Management',
       'Enterprise Data Analyst (Enterprise Portfolio Management Office)',
       'Lead Data Scientist – Network Analysis and Control',
       'Sr. Research Associate/ Scientist, NGS prep & Molecular Genomics',
       'Developer III - Data Science',
       'Hydrogen/Tritium Materials Scientist (Experienced)',
       'Data Scientist/Data Analytics Practitioner',
       'AI/ML - Machine Learning Scientist, Siri Understanding'],
      dtype=object)

In [88]:
print(df1['Job Title'].value_counts())

Data Scientist                                            326
Data Engineer                                              26
Senior Data Scientist                                      19
Machine Learning Engineer                                  15
Data Analyst                                               12
                                                         ...
Data Science Instructor                                     1
Business Data Analyst                                       1
Purification Scientist                                      1
Data Engineer, Enterprise Analytics                         1
AI/ML - Machine Learning Scientist, Siri Understanding      1
Name: Job Title, Length: 172, dtype: int64

In [89]:
# creating a function to simplify the data.
def new_title(title):
    if 'data scientist' in title.lower() or 'Data Science' in title.lower():
        return 'data scientist'
    elif 'data engineer' in title.lower():
        return 'data engineer'
    elif 'analyst' in title.lower():
        return 'analyst'
    elif 'machine learning' in title.lower():
        return 'machine learning '
    elif 'manager' in title.lower():
        return 'manager'
    elif 'director' in title.lower():
        return 'director'
    else:
        return 'other'
def prefix(title):
    if 'sr.' in title.lower() or 'senior' in title.lower() or 'sr' in title.lower() or 'lead' in title.lower() or 'principal' in title.lower():
            return 'senior'
    elif 'jr' in title.lower() or 'jr.' in title.lower():
        return 'jr'
    else:
        return 'nil'

In [90]:
# creating new colummn as new_title
df1['new_title'] = df1['Job Title'].apply(new_title)

In [91]:
# creating a new column as exp_level
df1['exp_level'] = df1['Job Title'].apply(prefix)

In [92]:
print(df1['new_title'].value_counts())
print('----------------------------------')
print(df1['exp_level'].value_counts())

data scientist       444
other                 69
analyst               55
data engineer         46
machine learning      35
manager                7
director               3
Name: new_title, dtype: int64
----------------------------------
nil       564
senior     93
jr          2
Name: exp_level, dtype: int64

First column is cleaned as new columns have been created based on it

In [93]:
# second column Salary Estimate	
df1['Salary Estimate'].unique()

array(['$137K-$171K (Glassdoor est.)', '$75K-$131K (Glassdoor est.)',
       '$79K-$131K (Glassdoor est.)', '$99K-$132K (Glassdoor est.)',
       '$90K-$109K (Glassdoor est.)', '$101K-$165K (Glassdoor est.)',
       '$56K-$97K (Glassdoor est.)', '$79K-$106K (Glassdoor est.)',
       '$71K-$123K (Glassdoor est.)', '$90K-$124K (Glassdoor est.)',
       '$91K-$150K (Glassdoor est.)', '$141K-$225K (Glassdoor est.)',
       '$145K-$225K(Employer est.)', '$79K-$147K (Glassdoor est.)',
       '$122K-$146K (Glassdoor est.)', '$112K-$116K (Glassdoor est.)',
       '$110K-$163K (Glassdoor est.)', '$124K-$198K (Glassdoor est.)',
       '$79K-$133K (Glassdoor est.)', '$69K-$116K (Glassdoor est.)',
       '$31K-$56K (Glassdoor est.)', '$95K-$119K (Glassdoor est.)',
       '$212K-$331K (Glassdoor est.)', '$66K-$112K (Glassdoor est.)',
       '$128K-$201K (Glassdoor est.)', '$138K-$158K (Glassdoor est.)',
       '$80K-$132K (Glassdoor est.)', '$87K-$141K (Glassdoor est.)',
       '$92K-$155K (Glassdoor est.)', '$105K-$167K (Glassdoor est.)'],
      dtype=object)

In [94]:
# first removing sting data in bracktes
df1['Salary Estimate'] = df1['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [95]:
df1['Salary Estimate'] = df1['Salary Estimate'].apply(lambda x: x.replace('K','').replace('$',''))
df1['min_salary'] = df1['Salary Estimate'].apply(lambda x: int(x.split('-')[0]))
df1['max_salary'] = df1['Salary Estimate'].apply(lambda x: int(x.split('-')[1]))
df1['avg_salary'] = (df1.min_salary+df1.max_salary)//2
df1.head()

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,new_title,exp_level,min_salary,max_salary,avg_salary
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",data scientist,senior,137,171,154
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,data scientist,nil,137,171,154
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,data scientist,nil,137,171,154
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",data scientist,nil,137,171,154
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",data scientist,nil,137,171,154

In [96]:
# cleaning 4th column Company Name	
df1['Company_Name'] = df1['Company Name'].apply(lambda x: x.split('\n')[0])
# new column 'Company_Name' is created

In [97]:
# cleaning 5th column Location	
df1['Location'].value_counts()

San Francisco, CA    58
New York, NY         50
Washington, DC       26
Boston, MA           24
Chicago, IL          22
                     ..
Lehi, UT              1
Culver City, CA       1
Lake Oswego, OR       1
New Orleans, LA       1
Irwindale, CA         1
Name: Location, Length: 207, dtype: int64

In [98]:
df1['Location'].unique()

array(['New York, NY', 'Chantilly, VA', 'Boston, MA', 'Newton, MA',
       'Santa Barbara, CA', 'Cambridge, MA', 'Bedford, MA',
       'San Diego, CA', 'Chicago, IL', 'Herndon, VA', 'Saint Louis, MO',
       'Richland, WA', 'Northbrook, IL', 'Washington, DC', 'Remote',
       'Memphis, TN', 'Plano, TX', 'West Grove, PA', 'Phoenix, AZ',
       'Appleton, WI', 'Atlanta, GA', 'Orlando, FL', 'Lexington, MA',
       'McLean, VA', 'San Francisco, CA', 'Sheboygan, WI',
       'United States', 'Bothell, WA', 'Lincoln, NE', 'Overland Park, KS',
       'Santa Monica, CA', 'Portsmouth, NH', 'Ewing, NJ',
       'South San Francisco, CA', 'Palo Alto, CA', 'Bellevue, WA',
       'New Orleans, LA', 'Akron, OH', 'Fort Wayne, IN', 'Woburn, MA',
       'Carson, CA', 'Coral Gables, FL', 'Santa Clara, CA',
       'Brisbane, CA', 'Winter Park, FL', 'Redwood City, CA',
       'Peoria, IL', 'Ipswich, MA', 'Carmel, IN', 'Emeryville, CA',
       'Gaithersburg, MD', 'Longmont, CO', 'Austin, TX', 'Yakima, WA',
       'Santa Cruz, CA', 'Springfield, VA', 'Alexandria, VA', 'Utah',
       'Reston, VA', 'Denver, CO', 'New Jersey', 'Aurora, CO',
       'Hill AFB, UT', 'Chandler, AZ', 'Indianapolis, IN',
       'Nashville, TN', 'Timonium, MD', 'Burlingame, CA',
       'Annapolis Junction, MD', 'Bethesda, MD', 'Dayton, OH',
       'Schaumburg, IL', 'Cupertino, CA', 'Lehi, UT', 'Culver City, CA',
       'Lake Oswego, OR', 'San Mateo, CA', 'Holyoke, MA',
       'Woodbridge, NJ', 'Dearborn, MI', 'Maryland Heights, MO',
       'Rockville, MD', 'Carpinteria, CA', 'Columbia, SC',
       'Hauppauge, NY', 'Fort Meade, MD', 'Columbia, MO', 'Vicksburg, MS',
       'Birmingham, AL', 'Blue Bell, PA', 'Cincinnati, OH',
       'Harrisburg, PA', 'Oak Ridge, TN', 'San Carlos, CA', 'Waltham, MA',
       'Fort Worth, TX', 'Smithfield, RI', 'Cedar Rapids, IA',
       'Fort Belvoir, VA', 'Linthicum Heights, MD', 'Maple Plain, MN',
       'Tulsa, OK', 'Baltimore, MD', 'Oklahoma City, OK',
       'Scotts Valley, CA', 'Spartanburg, SC', 'Hartford, CT',
       'Beavercreek, OH', 'Norfolk, VA', 'Charlotte, NC', 'Champaign, IL',
       'Texas', 'Hoboken, NJ', 'Lebanon, IN', 'Oakland, CA',
       'Melbourne, FL', 'Cleveland, OH', 'Norwell, MA', 'San Jose, CA',
       'Piscataway, NJ', 'Danvers, MA', 'Vienna, VA', 'Livermore, CA',
       'Pittsburgh, PA', 'Irvine, CA', 'Oshkosh, WI', 'Menlo Park, CA',
       'Dallas, TX', 'Arlington, VA', 'Monroe, WI', 'Sacramento, CA',
       'Hampton, VA', 'Richmond, VA', 'Monterey, CA', 'Woodlawn, MD',
       'Ann Arbor, MI', 'Concord, CA', 'Durham, NC', 'Kent, OH',
       'Laurel, MD', 'Columbia, MD', 'Falls Church, VA',
       'Thousand Oaks, CA', 'Edison, NJ', 'Adelphi, MD', 'Seattle, WA',
       'Sunnyvale, CA', 'Fremont, CA', 'Hamilton, NJ', 'Huntsville, AL',
       'Merrifield, VA', 'Madison, WI', 'Philadelphia, PA',
       'Winston-Salem, NC', 'Raleigh, NC', 'Burbank, CA', 'San Ramon, CA',
       'Oxnard, CA', 'Kansas City, MO', 'Jersey City, NJ',
       'Manchester, NH', 'Winters, TX', 'Brooklyn, NY', 'Germantown, MD',
       'Omaha, NE', 'Open Fork, VA', 'Ashburn, VA', 'Lombard, IL',
       'Alpharetta, GA', 'Boulder, CO', 'Mountain View, CA',
       'Trumbull, CT', 'Sterling, VA', 'Foster City, CA', 'Frederick, MD',
       'Colorado Springs, CO', 'Southfield, MI', 'San Clemente, CA',
       'The Woodlands, TX', 'Pleasanton, CA', 'Wilmington, DE',
       'Fort Sam Houston, TX', 'Lexington Park, MD',
       'Patuxent, Anne Arundel, MD', 'Fairfax, VA', 'San Antonio, TX',
       'Silver Spring, MD', 'Portland, OR', 'Simi Valley, CA',
       'New Bedford, MA', 'Rancho Cucamonga, CA', 'Collegeville, PA',
       'Minneapolis, MN', 'Gahanna, OH', 'California', 'Wellesley, MA',
       'Washington, VA', 'Orange, CA', 'Bridgeport, WV', 'Oakville, CA',
       'Naperville, IL', 'Houston, TX', 'Redmond, WA', 'West Chester, PA',
       'Quantico, VA', 'Fort Lee, NJ', 'Irwindale, CA'], dtype=object)

In [99]:
# merging state names --keeping only state names
df1['job_location'] = df1['Location'].apply(lambda x: x.split(',')[-1])
df1.head()

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,new_title,exp_level,min_salary,max_salary,avg_salary,Company_Name,job_location
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",data scientist,senior,137,171,154,Healthfirst,NY
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,data scientist,nil,137,171,154,ManTech,VA
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,data scientist,nil,137,171,154,Analysis Group,MA
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",data scientist,nil,137,171,154,INFICON,MA
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",data scientist,nil,137,171,154,Affinity Solutions,NY

In [100]:
df1['job_location'].unique()

array([' NY', ' VA', ' MA', ' CA', ' IL', ' MO', ' WA', ' DC', 'Remote',
       ' TN', ' TX', ' PA', ' AZ', ' WI', ' GA', ' FL', 'United States',
       ' NE', ' KS', ' NH', ' NJ', ' LA', ' OH', ' IN', ' MD', ' CO',
       'Utah', 'New Jersey', ' UT', ' OR', ' MI', ' SC', ' MS', ' AL',
       ' RI', ' IA', ' MN', ' OK', ' CT', ' NC', 'Texas', ' DE',
       'California', ' WV'], dtype=object)

In [101]:
# similary for headquaters
df1['Headquarters'].unique()

array(['New York, NY', 'Herndon, VA', 'Boston, MA',
       'Bad Ragaz, Switzerland', 'Santa Barbara, CA',
       'Basel, Switzerland', 'Bedford, MA', 'Mountain View, CA',
       'Chicago, IL', 'Mc Lean, VA', 'Saint Louis, MO', 'Richland, WA',
       'Northbrook, IL', 'Princeton, NJ', 'Mays Landing, NJ',
       'Washington, DC', 'Memphis, TN', 'Tempe, AZ', 'Reading, PA',
       'San Francisco, CA', 'Menlo Park, CA', 'Atlanta, GA',
       'Orlando, FL', 'Lexington, MA', 'Falls Church, VA',
       'Sheboygan, WI', 'Seattle, WA', 'Bellevue, WA', 'Lincoln, NE',
       'Chantilly, VA', 'Santa Monica, CA', 'Ewing, NJ',
       'South San Francisco, CA', 'Palo Alto, CA', 'Singapore, Singapore',
       'Cambridge, MA', 'OSAKA, Japan', 'Santa Clara, CA', 'Vienna, VA',
       'New Orleans, LA', 'Akron, OH', 'Zurich, Switzerland',
       'Woburn, MA', 'Carson, CA', 'Coral Gables, FL', 'San Ramon, CA',
       'Brisbane, CA', 'Winter Park, FL', 'San Rafael, CA',
       'Deerfield, IL', 'Ipswich, MA', 'Carmel, IN', 'Chevy Chase, MD',
       'Hartford, CT', 'Emeryville, CA', 'Cambridge, United Kingdom',
       'Rockville, MD', 'Minneapolis, MN', 'Austin, TX', 'Yakima, WA',
       'Santa Cruz, CA', 'South Jordan, UT', 'Reston, VA', 'Denver, CO',
       'Holmdel, NJ', 'Aurora, CO', 'San Mateo, CA', 'Goleta, CA',
       'Franklin, TN', 'Indianapolis, IN', 'Lutherville Timonium, MD',
       'Westminster, CO', 'Burlingame, CA', 'Annapolis Junction, MD',
       'Bethesda, MD', 'Beavercreek, OH', 'Schaumburg, IL',
       'Sunnyvale, CA', 'Lehi, UT', 'Lake Oswego, OR', 'Holyoke, MA',
       'Dulles, VA', 'San Diego, CA', 'Detroit, MI', 'Stamford, CT',
       'Carpinteria, CA', 'Columbia, SC', '-1', "Marcy-l'Etoile, France",
       'Columbia, MO', 'Fairfax, VA', 'Chandler, AZ', 'Aurora, Canada',
       'Blue Bell, PA', 'Troy, MI', 'Redwood City, CA', 'Greenville, SC',
       'Arlington, VA', 'Harrisburg, PA', 'Hamilton, Bermuda',
       'Lynchburg, VA', 'Springfield, MA', 'San Carlos, CA',
       'Waltham, MA', 'San Jose, CA', 'Jersey City, NJ', 'Fort Worth, TX',
       'Cedar Rapids, IA', 'McLean, VA', 'Lorton, VA', 'Maple Plain, MN',
       'Kent, WA', 'Woodbine, MD', 'San Antonio, TX', 'Scotts Valley, CA',
       'Spartanburg, SC', 'Woodbridge, NJ', 'Chennai, India',
       'Tel Aviv-Yafo, Israel', 'Baltimore, MD', 'Manalapan, NJ',
       'Charlotte, NC', 'Saxonburg, PA', 'Bristol, PA',
       'Bangalore, India', 'Hoboken, NJ', 'Paris, France',
       'Greenwich, CT', 'Santa Ana, CA', 'Houston, TX', 'Tucson, AZ',
       'Birmingham, AL', 'Cleveland, OH', 'Pleasanton, CA',
       'Columbus, OH', 'Piscataway, NJ', 'Danvers, MA',
       'Philadelphia, PA', 'Livermore, CA', 'Pittsburgh, PA',
       'Dallas, TX', 'Toronto, Canada', 'Irvine, CA', 'Hillsborough, NJ',
       'Oshkosh, WI', 'Fremont, CA', 'Monroe, WI', 'Goteborg, Sweden',
       'Lake Buena Vista, FL', 'Schaffhausen, Switzerland',
       'Richmond, VA', 'Newark, CA', 'Greensboro, NC', 'Scottsdale, AZ',
       'Irving, TX', 'Beltsville, MD', 'Naperville, IL',
       'Brentford, United Kingdom', 'Cincinnati, OH', 'Somerset, NJ',
       'London, United Kingdom', 'Raleigh, NC', 'Leesburg, VA',
       'Durham, NC', 'Kent, OH', 'Westlake Village, CA',
       'North Brunswick, NJ', 'Benicia, CA', 'Laurel, MD', 'Columbia, MD',
       'Danville, CA', 'Wilmington, MA', 'New York, 061', 'Reading, MA',
       'Folsom, CA', 'Wilsonville, OR', 'Huntsville, AL', 'Madison, WI',
       'Phila, PA', 'Winston-Salem, NC', 'Half Moon Bay, CA',
       'Los Angeles, CA', 'Hilliard, OH', 'Hanover, MD',
       'Kansas City, MO', 'Bengaluru, India', 'Alpharetta, GA',
       'Germantown, MD', 'Omaha, NE', 'Clifton Park, NY', 'Livonia, MI',
       'Ashburn, VA', 'Nashville, TN', 'Alexandria, VA', 'Edison, NJ',
       'Ventura, CA', 'Armonk, NY', 'Trumbull, CT', 'Chadds Ford, PA',
       'Saint Paul, MN', 'Glen Allen, VA', 'Aliso Viejo, CA',
       'Plainsboro, NJ', 'Fairmont, WV', 'Cherry Hill, NJ', 'Itasca, IL',
       'Coconut Creek, FL', 'Lombard, IL', 'Honolulu, HI',
       'Carle Place, NY', 'Cupertino, CA', 'Tampa, FL', 'Totowa, NJ',
       'Rome, NY', 'Milan, IL', 'Marbella, Spain', 'Simi Valley, CA',
       'Rancho Cucamonga, CA', 'Albuquerque, NM', 'Langley, VA',
       'Plano, TX', 'Albertville, AL', 'Orange, CA', 'Littleton, CO',
       'Oakville, Canada', 'San Bruno, CA', 'West Chester, PA',
       'Utica, MI', 'Fort Lee, NJ'], dtype=object)

In [102]:
df1['company_hq'] = df1['Headquarters'].apply(lambda x: x.split(',')[-1])

In [103]:
df1['company_hq'].unique()

array([' NY', ' VA', ' MA', ' Switzerland', ' CA', ' IL', ' MO', ' WA',
       ' NJ', ' DC', ' TN', ' AZ', ' PA', ' GA', ' FL', ' WI', ' NE',
       ' Singapore', ' Japan', ' LA', ' OH', ' IN', ' MD', ' CT',
       ' United Kingdom', ' MN', ' TX', ' UT', ' CO', ' OR', ' MI', ' SC',
       '-1', ' France', ' Canada', ' Bermuda', ' IA', ' India', ' Israel',
       ' NC', ' AL', ' Sweden', ' 061', ' WV', ' HI', ' Spain', ' NM'],
      dtype=object)

In [104]:
# replacing -1 with 'na'
df1['company_hq'] = df1['company_hq'].apply(lambda x :'na' if x=='-1' else x)

In [105]:
# cleaning size column
df1['Size'].unique()

array(['1001 to 5000 employees', '5001 to 10000 employees',
       '501 to 1000 employees', '51 to 200 employees', '10000+ employees',
       '201 to 500 employees', '1 to 50 employees', '-1', 'Unknown'],
      dtype=object)

In [106]:
df1['Size'] = df1['Size'].apply(lambda x :'unknown' if x=='-1' or x=='Unknown' else x)

In [107]:
df1['Size'].unique()

array(['1001 to 5000 employees', '5001 to 10000 employees',
       '501 to 1000 employees', '51 to 200 employees', '10000+ employees',
       '201 to 500 employees', '1 to 50 employees', 'unknown'],
      dtype=object)

In [108]:
df1['Founded'].value_counts()

-1       107
 2012     34
 2011     24
 2010     22
 1996     22
        ...
 1820      1
 1952      1
 1959      1
 1894      1
 1962      1
Name: Founded, Length: 103, dtype: int64

In [109]:
df1['company_age'] = df1['Founded'].apply(lambda x: x if x<1 else 2023-x)

In [111]:
# cleaning column Type of ownership
df1['Type of ownership'].unique()

array(['Nonprofit Organization', 'Company - Public',
       'Private Practice / Firm', 'Company - Private', 'Government',
       'Subsidiary or Business Segment', 'Other Organization', '-1',
       'Unknown', 'Hospital', 'Self-employed', 'College / University',
       'Contract'], dtype=object)

In [112]:
df1['Type of ownership'] = df1['Type of ownership'].apply(lambda x :'unknown' if x=='-1' or x=='Unknown' else x)

In [113]:
df1['Type of ownership'].unique()

array(['Nonprofit Organization', 'Company - Public',
       'Private Practice / Firm', 'Company - Private', 'Government',
       'Subsidiary or Business Segment', 'Other Organization', 'unknown',
       'Hospital', 'Self-employed', 'College / University', 'Contract'],
      dtype=object)

In [114]:
# cleaning 'Industry' column
df1['Industry'].unique()

array(['Insurance Carriers', 'Research & Development', 'Consulting',
       'Electrical & Electronic Manufacturing', 'Advertising & Marketing',
       'Computer Hardware & Software', 'Biotech & Pharmaceuticals',
       'Consumer Electronics & Appliances Stores',
       'Enterprise Software & Network Solutions', 'IT Services', 'Energy',
       'Chemical Manufacturing', 'Federal Agencies', 'Internet',
       'Health Care Services & Hospitals',
       'Investment Banking & Asset Management', 'Aerospace & Defense',
       'Utilities', '-1', 'Express Delivery Services',
       'Staffing & Outsourcing', 'Insurance Agencies & Brokerages',
       'Consumer Products Manufacturing', 'Industrial Manufacturing',
       'Food & Beverage Manufacturing', 'Banks & Credit Unions',
       'Video Games', 'Shipping', 'Telecommunications Services',
       'Lending', 'Cable, Internet & Telephone Providers', 'Real Estate',
       'Venture Capital & Private Equity', 'Miscellaneous Manufacturing',
       'Oil & Gas Services', 'Transportation Equipment Manufacturing',
       'Telecommunications Manufacturing', 'Transportation Management',
       'News Outlet', 'Architectural & Engineering Services',
       'Food & Beverage Stores', 'Other Retail Stores',
       'Hotels, Motels, & Resorts', 'State & Regional Agencies',
       'Financial Transaction Processing', 'Timber Operations',
       'Colleges & Universities', 'Travel Agencies', 'Accounting',
       'Logistics & Supply Chain', 'Farm Support Services',
       'Social Assistance', 'Construction',
       'Department, Clothing, & Shoe Stores', 'Publishing',
       'Health, Beauty, & Fitness', 'Wholesale', 'Rail'], dtype=object)

In [115]:
df1['Industry'] = df1['Industry'].apply(lambda x :'unknown' if x=='-1' or x=='Unknown' else x)

In [116]:
df1.drop('Company Name', axis=1, inplace=True)
df1.drop('Location', axis=1, inplace=True)
df1.drop('Founded', axis=1, inplace=True)

In [118]:
df1.drop('Job Title', axis=1, inplace=True)
df1.drop('Salary Estimate', axis=1, inplace=True)
df1.drop('Headquarters', axis=1, inplace=True)

In [119]:
df1.head()

,Job Description,Size,Type of ownership,Industry,Sector,Revenue,Competitors,new_title,exp_level,min_salary,max_salary,avg_salary,Company_Name,job_location,company_hq,company_age
0,Description\n\nThe Senior Data Scientist is re...,1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",data scientist,senior,137,171,154,Healthfirst,NY,NY,30
1,"Secure our Nation, Ignite your Future\n\nJoin ...",5001 to 10000 employees,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,data scientist,nil,137,171,154,ManTech,VA,VA,55
2,Overview\n\n\nAnalysis Group is one of the lar...,1001 to 5000 employees,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,data scientist,nil,137,171,154,Analysis Group,MA,MA,42
3,JOB DESCRIPTION:\n\nDo you have a passion for ...,501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",data scientist,nil,137,171,154,INFICON,MA,Switzerland,23
4,Data Scientist\nAffinity Solutions / Marketing...,51 to 200 employees,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",data scientist,nil,137,171,154,Affinity Solutions,NY,NY,25

In [120]:
# cleaning 'Competitors' column
df1['Competitors'].value_counts()

-1                                                                488
Roche, GlaxoSmithKline, Novartis                                   10
Los Alamos National Laboratory, Battelle, SRI International         6
Leidos, CACI International, Booz Allen Hamilton                     6
MIT Lincoln Laboratory, Lockheed Martin, Northrop Grumman           3
                                                                 ...
Pfizer, GlaxoSmithKline                                             1
Square, Amazon, Apple                                               1
Lumentum Operations, Keysight Technologies, O-Net Technologies      1
Munich Re, Hannover RE, SCOR                                        1
Genomic Health, Myriad Genetics, The Broad Institute                1
Name: Competitors, Length: 108, dtype: int64

In [121]:
df1['Competitors'] = df1['Competitors'].apply(lambda x :'unknown' if x=='-1' else x)

In [122]:
# now analysing and cleaning 'Job Description'
df1['Job Description'][0]

"Description\n\nThe Senior Data Scientist is responsible for defining, building, and improving statistical models to improve business processes and outcomes in one or more healthcare domains such as Clinical, Enrollment, Claims, and Finance. As part of the broader analytics team, Data Scientist will gather and analyze data to solve and address complex business problems and evaluate scenarios to make predictions on future outcomes and work with the business to communicate and support decision-making. This position requires strong analytical skills and experience in analytic methods including multivariate regressions, hierarchical linear models, regression trees, clustering methods and other complex statistical techniques.\n\nDuties & Responsibilities:\n\n• Develops advanced statistical models to predict, quantify or forecast various operational and performance metrics in multiple healthcare domains\n• Investigates, recommends, and initiates acquisition of new data resources from internal and external sources\n• Works with multiple teams to support data collection, integration, and retention requirements based on business needs\n• Identifies critical and emerging technologies that will support and extend quantitative analytic capabilities\n• Collaborates with business subject matter experts to select relevant sources of information\n• Develops expertise with multiple machine learning algorithms and data science techniques, such as exploratory data analysis and predictive modeling, graph theory, recommender systems, text analytics and validation\n• Develops expertise with Healthfirst datasets, data repositories, and data movement processes\n• Assists on projects/requests and may lead specific tasks within the project scope\n• Prepares and manipulates data for use in development of statistical models\n• Other duties as assigned\n\nMinimum Qualifications:\n\n-Bachelor's Degree\n\nPreferred Qualifications:\n\n- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience\n\nMinimum Qualifications:\n\n-Bachelor's Degree\n\nPreferred Qualifications:\n\n- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience\n\nWE ARE AN EQUAL OPPORTUNITY EMPLOYER. Applicants and employees are considered for positions and are evaluated without regard to mental or physical disability, race, color, religion, gender, national origin, age, genetic information, military or veteran status, sexual orientation, marital status or any other protected Federal, State/Province or Local status unrelated to the performance of the work involved.\n\nIf you have a disability under the Americans with Disability Act or a similar law, and want a reasonable accommodation to assist with your job search or application for employment, please contact us by sending an email to careers@Healthfirst.org or calling 212-519-1798 . In your email please include a description of the accommodation you are requesting and a description of the position for which you are applying. Only reasonable accommodation requests related to applying for a position within Healthfirst Management Services will be reviewed at the e-mail address and phone number supplied. Thank you for considering a career with Healthfirst Management Services.\nEEO Law Poster and Supplement\n\n]]>"

In [123]:
df1['python'] = df1['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df1['sql'] = df1['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0)
df1['ml_dl'] = df1['Job Description'].apply(lambda x: 1 if 'machine learning' in x.lower() or 'deep learning' in x.lower() else 0)
df1['excel'] = df1['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df1['hadoop'] = df1['Job Description'].apply(lambda x: 1 if 'hadoop' in x.lower() else 0)
df1['spark'] = df1['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df1['cloud_platform'] = df1['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() or 'azure' in x.lower() else 0)
df1['business_intelligence'] = df1['Job Description'].apply(lambda x: 1 if 'tableau' in x.lower() or 'power bi' in x.lower() else 0)
df1['big_data'] = df1['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)

In [125]:
# cleaning 'revenue' column
df1['Revenue'].unique()

array(['Unknown / Non-Applicable', '$1 to $2 billion (USD)',
       '$100 to $500 million (USD)', '$10+ billion (USD)',
       '$2 to $5 billion (USD)', '$500 million to $1 billion (USD)',
       '$5 to $10 billion (USD)', '$10 to $25 million (USD)',
       '$25 to $50 million (USD)', '$50 to $100 million (USD)',
       '$1 to $5 million (USD)', '$5 to $10 million (USD)',
       'Less than $1 million (USD)', '-1'], dtype=object)

In [126]:
df1['Revenue'] = df1['Revenue'].apply(lambda x :'unknown' if x=='-1' or x=='Unknown / Non-Applicable' else x)

In [128]:
df1.drop('Job Description', axis=1, inplace=True)

In [129]:
df1.head()

,Size,Type of ownership,Industry,Sector,Revenue,Competitors,new_title,exp_level,min_salary,max_salary,...,company_age,python,sql,ml_dl,excel,hadoop,spark,cloud_platform,business_intelligence,big_data
0,1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,Insurance,unknown,"EmblemHealth, UnitedHealth Group, Aetna",data scientist,senior,137,171,...,30,0,0,1,0,0,0,1,0,0
1,5001 to 10000 employees,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),unknown,data scientist,nil,137,171,...,55,0,1,1,0,1,0,0,0,1
2,1001 to 5000 employees,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),unknown,data scientist,nil,137,171,...,42,1,0,1,1,0,0,1,0,0
3,501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",data scientist,nil,137,171,...,23,1,1,1,1,0,0,1,0,0
4,51 to 200 employees,Company - Private,Advertising & Marketing,Business Services,unknown,"Commerce Signals, Cardlytics, Yodlee",data scientist,nil,137,171,...,25,1,1,1,1,0,0,0,0,0

In [131]:
df1.shape

(659, 24)

# Elementry data analysis

In [132]:
# basic EDA using pandas profiler
! pip install pandas-profiling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandas-profiling
  Downloading pandas_profiling-3.6.6-py2.py3-none-any.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 8.1 MB/s eta 0:00:00
Collecting ydata-profiling (from pandas-profiling)
  Downloading ydata_profiling-4.2.0-py2.py3-none-any.whl (352 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.3/352.3 kB 29.6 MB/s eta 0:00:00
Requirement already satisfied: scipy<1.11,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<2,>1.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib<4,>=3.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Requirement already satisfied: pydantic<2,>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.10.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Collecting visions[type_image_path]==0.7.5 (from ydata-profiling->pandas-profiling)
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 9.6 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.24,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.22.4)
Collecting htmlmin==0.1.12 (from ydata-profiling->pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling->pandas-profiling)
  Downloading phik-0.12.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (679 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 kB 40.2 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (2.27.1)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling->pandas-profiling)
  Downloading multimethod-1.9.1-py3-none-any.whl (10 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.13.5)
Collecting typeguard<3,>=2.13.2 (from ydata-profiling->pandas-profiling)
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Collecting imagehash==4.3.1 (from ydata-profiling->pandas-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 24.1 MB/s eta 0:00:00
Collecting wordcloud>=1.9.1 (from ydata-profiling->pandas-profiling)
  Downloading wordcloud-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (455 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.4/455.4 kB 28.4 MB/s eta 0:00:00
Collecting dacite>=1.8 (from ydata-profiling->pandas-profiling)
  Downloading dacite-1.8.1-py3-none-any.whl (14 kB)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.4.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (8.4.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.1)
Collecting tangled-up-in-unicode>=0.0.4 (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling)
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 51.9 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.4.0,<2,>1.1->ydata-profiling->pandas-profiling) (2022.7.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<2,>=1.8.1->ydata-profiling->pandas-profiling) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=87153345faf6bd7e5b2f7153d2c6bb819da7196f0d19acb204c6f4514083f5cc
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
Installing collected packages: htmlmin, typeguard, tangled-up-in-unicode, multimethod, dacite, imagehash, wordcloud, visions, phik, ydata-profiling, pandas-profiling
  Attempting uninstall: wordcloud
    Found existing installation: wordcloud 1.8.2.2
    Uninstalling wordcloud-1.8.2.2:
      Successfully uninstalled wordcloud-1.8.2.2
Successfully installed dacite-1.8.1 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.9.1 pandas-profiling-3.6.6 phik-0.12.3 tangled-up-in-unicode-0.2.0 typeguard-2.13.3 visions-0.7.5 wordcloud-1.9.2 ydata-profiling-4.2.0

In [133]:
from pandas_profiling import ProfileReport
prof=ProfileReport(df1)
prof.to_file(output_file='df1_output.html')

<ipython-input-133-84cb2d54ee17>:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]